FROM maven:3.6-jdk-8-alpine AS builder
WORKDIR /common
COPY ./voecommerce/pom.xml .
RUN mvn -e -B dependency:resolve
COPY ./voecommerce/src ./src
RUN mvn clean install -DskipTests
WORKDIR /app
COPY ./checkoutecommerce/pom.xml .
RUN mvn -e -B dependency:resolve
COPY ./checkoutecommerce/src ./src
RUN mvn -e -B package -DskipTests
FROM openjdk:8-jre-alpine
COPY --from=builder /app/target/checkoutecommerce-0.0.1-SNAPSHOT.jar /
EXPOSE 7002
CMD ["java", "-jar","/checkoutecommerce-0.0.1-SNAPSHOT.jar"]