spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/ecommercelogisticbd
    username: ecommercelogistic
    password: ecommercelogistic
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
server:
  port: 7001